import type { OrbitalModel, RotationModel, TIMEZONE } from '../orbital-model';
import { Tempo } from '../time';
export declare function solar_phase(sunny: OrbitalModel, phase: number, near: number): number;
export declare function solar_term(sunny: OrbitalModel, dayMsec: number, dayZero: number, utc: number, phase: number): Tempo;
export declare function solar_phase_before(sunny: OrbitalModel, phase: number, utc: number): number;
export declare function solar_terms(sunny: OrbitalModel, dayMsec: number, dayZero: number, utc: number): {
    立春: Tempo;
    入梅: Tempo;
    春分: Tempo;
    半夏生: Tempo;
    夏土用: Tempo;
    立夏: Tempo;
    夏至: Tempo;
    秋土用: Tempo;
    立秋: Tempo;
    秋分: Tempo;
    冬土用: Tempo;
    立冬: Tempo;
    冬至: Tempo;
    春土用: Tempo;
    次立春: Tempo;
};
export declare function noon(sunny: OrbitalModel, dayMsec: number, dayZero: number, yearMsec: number, seasonZero: number, utc: number, day?: Tempo): {
    center_at: number;
    T0: Tempo;
    T1: Tempo;
    季節: number;
    南中差分: number;
    南中時刻: number;
    真夜中: number;
    label?: string;
    table?: number[];
    zero: number;
    write_at: number;
    now_idx: number;
    last_at: number;
    next_at: number;
};
export declare function solor(sunny: OrbitalModel, earthy: RotationModel, geo: TIMEZONE, dayMsec: number, dayZero: number, yearMsec: number, seasonZero: number, utc: number, idx?: number, solarNoon?: {
    center_at: number;
    T0: Tempo;
    T1: Tempo;
    季節: number;
    南中差分: number;
    南中時刻: number;
    真夜中: number;
    label?: string;
    table?: number[];
    zero: number;
    write_at: number;
    now_idx: number;
    last_at: number;
    next_at: number;
}): import("../orbital-model").SolarObservation | {
    K: number;
    lat: number;
    時角: number;
    方向: number;
    高度: number;
    真夜中: number;
    日の出: number;
    南中時刻: number;
    日の入: number;
};
export declare function 雑節_by_phase(sunny: OrbitalModel, dayMsec: number, dayZero: number, day10Zero: number, stemLength: number, utc: number): {
    立春: Tempo;
    立夏: Tempo;
    立秋: Tempo;
    立冬: Tempo;
    冬至: Tempo;
    春分: Tempo;
    夏至: Tempo;
    秋分: Tempo;
    入梅: Tempo;
    半夏生: Tempo;
    春: Tempo;
    夏: Tempo;
    秋: Tempo;
    冬: Tempo;
    春社日: Tempo;
    秋社日: Tempo;
    春土用: Tempo;
    夏土用: Tempo;
    秋土用: Tempo;
    冬土用: Tempo;
    春節分: Tempo;
    夏節分: Tempo;
    秋節分: Tempo;
    冬節分: Tempo;
    節分: Tempo;
    春彼岸: Tempo;
    秋彼岸: Tempo;
    八十八夜: Tempo;
    二百十日: Tempo;
    二百二十日: Tempo;
};
export declare function to_tempo_by_solor(sunny: OrbitalModel, earthy: RotationModel, geo: TIMEZONE, dayMsec: number, dayZero: number, yearMsec: number, seasonZero: number, hourLength: number, utc: number, day: Tempo): Tempo;
