import type { LunarApsisKind, LunarNodeKind, OrbitalModel, RotationModel, SPOT, TIMEZONE } from './orbital-model';
import type { LunisolarDate } from './phenomena/lunisolar';
import { Tempo } from './time';
export { EarthMoonOrbital, EarthSolarOrbital } from './naoj';
export type { EarthMoonOrbitalOptions, EarthSolarOrbitalOptions } from './naoj';
export { MeanOrbital, MeanRotation, TransformedOrbital, transformOrbital } from './mean';
export type { LunisolarDate, LunisolarPrincipalTerm } from './phenomena/lunisolar';
export type { PreparedSpot, PreparedSpotModels } from './prepare';
export { prepareSpot, prepareSpotModels } from './prepare';
export * from './orbital-model';
export type ERA = readonly [string, number, string?];
export type ERA_WITH_YEAR = readonly [string, number, number];
type ALL_DIC = ALGO_DIC | 'D' | 'G' | 'J' | 'Q' | 'Y' | 'b' | 'c' | 'd' | 'p' | 'u' | 'w' | 'x' | 'y';
type ALGO_DIC = 'A' | 'B' | 'C' | 'E' | 'F' | 'H' | 'M' | 'N' | 'S' | 'V' | 'Z' | 'a' | 'd' | 'f' | 'm' | 's';
type MSEC_CALC = 'period' | 'year' | 'season' | 'month' | 'moon' | 'week' | 'day' | 'hour' | 'minute' | 'second' | 'msec';
type RANGE_CALC = 'year' | 'month' | 'hour' | 'minute' | 'second';
type ZERO_CALC = 'period' | 'era' | 'year60' | 'year12' | 'year10' | 'year_s' | 'spring' | 'season' | 'moon' | 'week' | 'day60' | 'day28' | 'day12' | 'day10' | 'day_9' | 'day' | 'jd';
export type TempoDiff = TOKENS<ALL_DIC, number>;
export type TempoIdxs = TOKENS<ALL_DIC, number> & {
    M_is_leap: boolean;
};
type TempoMonth = {
    is_leap: boolean;
};
export type Unit = 'year' | 'month' | 'day' | 'hour' | 'minute' | 'second' | 'msec';
export type Precision = 'y' | 'M' | 'd' | 'H' | 'm' | 's' | 'S';
export type SpanPart = {
    unit: Unit;
    value: number;
    label: string;
};
export type Span = {
    unit: Unit;
    value: number;
    label: string;
    parts?: readonly SpanPart[];
};
export type SpanOptions = {
    precise?: boolean | Precision;
};
export type SpanLike = string | Span | SpanPart | readonly SpanPart[];
export type RelativeTimeUnit = Unit;
export type RelativeTimePrecision = Precision;
export type RelativeTimeDistancePart = SpanPart;
export type RelativeTimeDistance = Span;
export type RelativeTimeDistanceOptions = SpanOptions;
export type RelativeTimeAddition = SpanLike;
export type Tempos = {
    Zz: Tempo;
    A: Tempo;
    B: Tempo;
    C: Tempo;
    D: Tempo;
    E: Tempo;
    F: Tempo;
    G: Tempo;
    H: Tempo;
    J: Tempo;
    M: Tempo & TempoMonth;
    N: Tempo | undefined;
    Q: Tempo;
    S: Tempo;
    V: Tempo;
    Y: Tempo;
    Z: Tempo;
    a: Tempo;
    b: Tempo;
    c: Tempo;
    d: Tempo;
    f: Tempo;
    m: Tempo;
    p: Tempo | undefined;
    s: Tempo;
    u: Tempo;
    w: Tempo;
    x: Tempo | undefined;
    y: Tempo;
};
type DateInput = number | Tempos | string;
type NUMBER_RANGE = [number, number?];
type MEASURE = {
    range: NUMBER_RANGE;
    msec: number;
};
type FindMatcher = string | RegExp;
export type FindCondition = {
    note: FindMatcher;
} | {
    [format: string]: FindMatcher;
};
type FindBetween = readonly [from: number, to: number];
type IIDX = TOKENS<ALL_DIC, Indexer>;
type IDIC = IIDX & {
    parse: string;
    format: string;
    sunny: OrbitalModel;
    moony?: OrbitalModel;
    earthy: RotationModel;
    geo: TIMEZONE;
    era: string;
    eras: readonly ERA[];
    month_divs: number[];
    leaps: number[];
    start: [string, string, number];
    is_solor: boolean;
};
type ICALC = {
    eras: ERA_WITH_YEAR[];
    idx: TOKENS<ALL_DIC, number>;
    zero: TOKENS<ZERO_CALC, number>;
    msec: TOKENS<MSEC_CALC, number> & {
        moon?: number;
    };
    range: TOKENS<RANGE_CALC, [number, number]>;
};
type TOKENS<K extends string, T> = {
    [key in K]: T;
};
type IndexFactory = (this: Indexer, s: string) => number;
type LabelFactory = (list: readonly string[] | null, val: Tempo & {
    is_leap: boolean;
}, size: number) => string;
type IndexerProps = [] | [number] | readonly [readonly string[], readonly string[] | null] | readonly [readonly string[], readonly string[] | null, string | readonly string[]];
declare class Indexer {
    tempo?: Tempo;
    list: readonly string[];
    rubys: readonly string[];
    relatives?: string | readonly string[];
    length: number;
    zero: number;
    regex: string;
    regex_o: string;
    to_idx: IndexFactory;
    to_value: LabelFactory;
    to_label: LabelFactory;
    to_ruby: LabelFactory;
    constructor(arg: IndexerProps);
}
export declare class FancyDate {
    dic: IDIC;
    calc: ICALC;
    is_table_leap: boolean;
    is_table_month: boolean;
    strategy: string;
    table: {
        range: {
            year: number[];
            month: {
                [key: number]: number[];
            };
        };
        msec: {
            era: number[];
            year: number[];
            period: MEASURE;
            month: {
                [key: number]: number[];
            };
        };
    };
    constructor(o?: FancyDate);
    spot(...spot: SPOT): this;
    lang(parse: string, format: string): this;
    era(era: string, past: string, eras?: readonly ERA[]): this;
    calendar(start?: (string | number)[], leaps?: number[] | null, month_divs?: (number | null)[] | null): this;
    algo(o: Partial<TOKENS<ALGO_DIC, IndexerProps>>): this;
    daily(is_solor?: string | boolean): this;
    init(): this;
    yeary_table(utc: number): [string, string, string, string, (string[] | undefined)?][];
    monthry_table(utc: number): [string, string, string, string, (string[] | undefined)?][];
    weekly_table(utc: number): [string, string, string, string, (string[] | undefined)?][];
    time_table(utc: number): [string, string, string, string, (string[] | undefined)?][];
    solar_phase(phase: number, near: number): number;
    lunar_phase(phase: number, near: number): number;
    lunisolar(utc: number): LunisolarDate;
    solar_term(utc: number, phase: number): Tempo;
    solar_phase_before(phase: number, utc: number): number;
    solar_terms(utc: number): {
        立春: Tempo;
        入梅: Tempo;
        春分: Tempo;
        半夏生: Tempo;
        夏土用: Tempo;
        立夏: Tempo;
        夏至: Tempo;
        秋土用: Tempo;
        立秋: Tempo;
        秋分: Tempo;
        冬土用: Tempo;
        立冬: Tempo;
        冬至: Tempo;
        春土用: Tempo;
        次立春: Tempo;
    };
    succ_index(diff: string): TempoIdxs;
    back_index(diff: string): TempoIdxs;
    succ_msec(utc: number, diff: SpanLike): number;
    back_msec(utc: number, diff: SpanLike): number;
    succ(utc: DateInput, diff: SpanLike): number;
    back(utc: DateInput, diff: SpanLike): number;
    slide(utc: number, diff?: TempoDiff): number;
    parse(tgt: string | TempoIdxs, str?: string): number;
    parse_obj(tgt: string | TempoIdxs, str?: string): TempoIdxs;
    format(utc: DateInput, str?: string): string;
    add(utc: DateInput, span: SpanLike): number;
    add_obj(utc: DateInput, span: SpanLike): Tempos;
    sub(utc: DateInput, span: SpanLike): number;
    sub_obj(utc: DateInput, span: SpanLike): Tempos;
    span(to: DateInput, from?: DateInput | SpanOptions, options?: SpanOptions): string;
    span_obj(to: DateInput, from?: DateInput | SpanOptions, options?: SpanOptions): Span;
    relative_time_obj(text: string): Span;
    relative_time_add(utc: DateInput, distance: SpanLike): number;
    private add_span;
    relative_time_parse(text: string): Span;
    private span_like_parts;
    private invert_span_like;
    private parse_relative_time_part;
    private relative_time_target_digits;
    private normalize_relative_time_target_digits;
    private relative_time_unit_msec;
    private find_time_by_relative_digits;
    private find_relative_time_month;
    private find_relative_time_year_start;
    private find_time_in_day_by_relative_digits;
    private compare_relative_time_digits;
    private relative_time_interval_for_rank;
    private relative_time_source_since;
    private clamp_relative_time_since;
    find(unit: keyof Tempos, between: FindBetween, conditions: readonly FindCondition[]): number[];
    relative_time_distance(from: number, to?: number, { precise }?: RelativeTimeDistanceOptions): RelativeTimeDistance;
    private with_relative_time_anchor;
    private relative_time_distance_precise;
    private relative_time_parts;
    private relative_time_part_label;
    private relative_time_distance_fixed;
    private count_full_years;
    private count_full_months;
    private is_before_year_anniversary;
    private count_tempo_boundaries;
    match_find_condition(utc: number, condition: FindCondition): boolean;
    match_find_value(value: string, matcher: FindMatcher): boolean;
    private to_utc;
    private to_tempos_input;
    private is_tempos;
    private span_from_options;
    private is_span_options;
    private is_span_text;
    dup(): FancyDate;
    def_regex(): void;
    def_to_idx(): void;
    def_to_label(): void;
    def_calc(): void;
    def_eras(): void;
    def_year_table(): void;
    def_month_table(): void;
    def_table(): void;
    def_idx(): void;
    def_zero(): void;
    precision(): {
        strategy: string;
        year: number[][];
        day: [number, number][];
        leap: number[];
        is_legal_solor: boolean;
        is_legal_eto: boolean;
        is_legal_ETO: boolean;
    };
    noon(utc: any, day?: Tempo): {
        center_at: number;
        T0: Tempo;
        T1: Tempo;
        季節: number;
        南中差分: number;
        南中時刻: number;
        真夜中: number;
        label?: string;
        table?: number[];
        zero: number;
        write_at: number;
        now_idx: number;
        last_at: number;
        next_at: number;
    };
    solor(utc: any, idx?: number, solarNoon?: {
        center_at: number;
        T0: Tempo;
        T1: Tempo;
        季節: number;
        南中差分: number;
        南中時刻: number;
        真夜中: number;
        label?: string;
        table?: number[];
        zero: number;
        write_at: number;
        now_idx: number;
        last_at: number;
        next_at: number;
    }): import("./orbital-model").SolarObservation | {
        K: number;
        lat: number;
        時角: number;
        方向: number;
        高度: number;
        真夜中: number;
        日の出: number;
        南中時刻: number;
        日の入: number;
    };
    lunar(utc: any, day?: Tempo): import("./orbital-model").LunarObservation;
    lunar_apsis(kind: LunarApsisKind, near: number): import("./orbital-model").LunarApsis;
    lunar_node(kind: LunarNodeKind, near: number): import("./orbital-model").LunarNode;
    節句(utc: number, { M, d, B, E }?: Tempos): {
        カトリック: {
            万聖節: number[];
            万霊節: number[];
        };
        節句: {
            人日: number[];
            初午: (number | undefined)[];
            上巳: number[];
            端午: number[];
            七夕: number[];
            重陽: number[];
        };
        仏教: {
            灌仏会: number[];
            盂蘭盆会: number[];
        };
        風習: {
            小正月: number[];
            十五夜: number[];
            十三夜: number[];
            七五三: number[];
            正月事始め: number[];
        };
    };
    雑節(utc: number, { Zz, u, d }?: Tempos): {
        立春: Tempo;
        立夏: Tempo;
        立秋: Tempo;
        立冬: Tempo;
        冬至: Tempo;
        春分: Tempo;
        夏至: Tempo;
        秋分: Tempo;
        入梅: Tempo;
        半夏生: Tempo;
        春: Tempo;
        夏: Tempo;
        秋: Tempo;
        冬: Tempo;
        春社日: Tempo;
        秋社日: Tempo;
        春土用: Tempo;
        夏土用: Tempo;
        秋土用: Tempo;
        冬土用: Tempo;
        春節分: Tempo;
        夏節分: Tempo;
        秋節分: Tempo;
        冬節分: Tempo;
        節分: Tempo;
        春彼岸: Tempo;
        秋彼岸: Tempo;
        八十八夜: Tempo;
        二百十日: Tempo;
        二百二十日: Tempo;
    };
    雑節_by_phase(utc: number): {
        立春: Tempo;
        立夏: Tempo;
        立秋: Tempo;
        立冬: Tempo;
        冬至: Tempo;
        春分: Tempo;
        夏至: Tempo;
        秋分: Tempo;
        入梅: Tempo;
        半夏生: Tempo;
        春: Tempo;
        夏: Tempo;
        秋: Tempo;
        冬: Tempo;
        春社日: Tempo;
        秋社日: Tempo;
        春土用: Tempo;
        夏土用: Tempo;
        秋土用: Tempo;
        冬土用: Tempo;
        春節分: Tempo;
        夏節分: Tempo;
        秋節分: Tempo;
        冬節分: Tempo;
        節分: Tempo;
        春彼岸: Tempo;
        秋彼岸: Tempo;
        八十八夜: Tempo;
        二百十日: Tempo;
        二百二十日: Tempo;
    };
    to_tempo_by_solor(utc: number, day: any): Tempo;
    note(utc: number, tempos?: Tempos, arg1?: {
        立春: Tempo;
        立夏: Tempo;
        立秋: Tempo;
        立冬: Tempo;
        冬至: Tempo;
        春分: Tempo;
        夏至: Tempo;
        秋分: Tempo;
        入梅: Tempo;
        半夏生: Tempo;
        春: Tempo;
        夏: Tempo;
        秋: Tempo;
        冬: Tempo;
        春社日: Tempo;
        秋社日: Tempo;
        春土用: Tempo;
        夏土用: Tempo;
        秋土用: Tempo;
        冬土用: Tempo;
        春節分: Tempo;
        夏節分: Tempo;
        秋節分: Tempo;
        冬節分: Tempo;
        節分: Tempo;
        春彼岸: Tempo;
        秋彼岸: Tempo;
        八十八夜: Tempo;
        二百十日: Tempo;
        二百二十日: Tempo;
    }, arg2?: {
        カトリック: {
            万聖節: number[];
            万霊節: number[];
        };
        節句: {
            人日: number[];
            初午: (number | undefined)[];
            上巳: number[];
            端午: number[];
            七夕: number[];
            重陽: number[];
        };
        仏教: {
            灌仏会: number[];
            盂蘭盆会: number[];
        };
        風習: {
            小正月: number[];
            十五夜: number[];
            十三夜: number[];
            七五三: number[];
            正月事始め: number[];
        };
    }): string[];
    to_tempos(utc: number): Tempos;
    get_dic(tgt: string, tokens: string[], reg: RegExp): TempoIdxs;
    get_diff(src: string, f: {
        (num: string | null): number;
    }): TempoIdxs;
    index(src: string, str?: string, _disuse?: number): TempoIdxs;
    regex(tokens: any): RegExp;
    to_table(utc: number, bk: string, ik: string, has_notes?: boolean): [string, string, string, string, (string[] | undefined)?][];
    parse_by(data: TempoIdxs, diff?: TempoDiff): number;
    format_by(tempos: Tempos, str?: string): string;
    slide_by(o: Tempos, diff?: TempoDiff): number;
    tree(): (Indexer | (string[] | Indexer[])[])[];
}
