"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.二十四節季 = exports.二十八宿かな = exports.二十八宿 = exports.二十七宿かな = exports.二十七宿 = exports.九曜かな = exports.九曜 = exports.九星かなrev = exports.九星かな = exports.九星rev = exports.九星 = exports.七曜かな = exports.七曜 = exports.七巻冊子元号 = exports.ロムルス月ラベル数値かな = exports.ロムルス月ラベル数値 = exports.ロムルス月ラベルラテン語かな = exports.ロムルス月ラベルラテン語 = exports.マヤハアブ日 = exports.マヤハアブ = exports.マヤツォルキン = exports.マケマケ = exports.ヒイアカ = exports.ハウメア = exports.ナマカ = exports.トリトン = exports.ディスノミア = exports.チタニア = exports.タイタン = exports.セレス = exports.コプト月名 = exports.ガニメデ = exports.カロン = exports.カリスト = exports.エリス = exports.エジプト月名 = exports.zürich = exports.mayaTzolkin = exports.mayaLongCount = exports.mayaHaab = exports.Romus = exports.Paris = exports.NewYork_Summer = exports.NewYork = exports.Madurai = exports.London = exports.Jaypore = exports.Calendar = exports.Cairo = exports.Alexandria = void 0;
exports.金剛寺文書元号 = exports.西方百虎かな = exports.西方百虎 = exports.続史愚抄元号 = exports.皇代記元号 = exports.白分月 = exports.火星 = exports.海王星 = exports.水星 = exports.東方青龍かな = exports.東方青龍 = exports.東京 = exports.木星 = exports.月相かな = exports.月相 = exports.月 = exports.時鐘かな = exports.時鐘 = exports.太陽 = exports.太歳 = exports.天王星 = exports.天文火星 = exports.天文東京 = exports.天文月 = exports.天文地球 = exports.天文 = exports.地球 = exports.土星 = exports.和風月名かな = exports.和風月名 = exports.史料初出元号 = exports.南朝編年記略元号 = exports.南朝公卿補任元号 = exports.南朝元号 = exports.南方紀伝元号 = exports.南方朱雀かな = exports.南方朱雀 = exports.十干かな = exports.十干 = exports.十二支かな = exports.十二支 = exports.北朝元号 = exports.北方玄武かな = exports.北方玄武 = exports.冥王星 = exports.六曜かな = exports.六曜 = exports.元号 = exports.伊勢之巻元号 = exports.二十四節季かな = void 0;
exports.SubdivideTempoRule = exports.StartAlignedTempoRule = exports.SolarDayHourTempoRule = exports.SolarEventDayTempoRule = exports.RealSunsetDayTempoRule = exports.OrbitalPhaseTempoRule = exports.ObservedLunisolarYearRule = exports.ObservedLunisolarMonthRule = exports.MeanLunisolarMonthRule = exports.MeanLunarPhaseTempoRule = exports.FloorTempoRule = exports.FixedTempoRule = exports.EraAdjustedTempoRule = exports.CyclicDayTempoRule = exports.CachedTempoRule = exports.to_timezone_deg = exports.to_tempo_by = exports.to_tempo_bare = exports.to_sec = exports.to_msec = exports.localTimezoneDeg = exports.SECOND = exports.MINUTE = exports.HOUR = exports.DAY = exports.transformOrbital = exports.rotationOf = exports.resolveSkyBody = exports.prepareSpotModels = exports.prepareSpot = exports.placeStar = exports.placeSatellite = exports.placePlanet = exports.orbitalOf = exports.isPlanetSkyBody = exports.hasSolarEvents = exports.hasLunarOrbitEvents = exports.hasLunarEvents = exports.centerOf = exports.bodyProfileOf = exports.TransformedOrbital = exports.MeanRotation = exports.MeanOrbital = exports.MarsSolarOrbital = exports.EarthSolarOrbital = exports.EarthMoonOrbital = exports.FancyDate = exports.黒分月軌道 = exports.黒分月 = exports.金星 = void 0;
exports.listLocales = exports.getLocale = exports.SCRIPT_REGISTRY = exports.LOCALE_REGISTRY = exports.roman = exports.old_jpn = exports.mod = exports.kor = exports.jpn = exports.english = exports.arabic = exports.angle = exports.DIC = exports.join = exports.envelope_of = exports.cyclic_label = exports.Tempo = exports.TableTempoRule = void 0;
// export * from はコンパイル時に tslib.__exportStar(require(...), exports) という
// 実行時関数呼び出しになり、静的な named export 解析に依存するバンドラ
// (Cloudflare Workers 等、esbuild/Rollup 系)では再エクスポートされた名前が
// 検出できず undefined になる不具合があった(実測: svelte-tick-timer を
// Cloudflare Workers にデプロイした際に "Cannot read properties of undefined
// (reading 'to_msec')" で発覚。development-notes.md 参照)。
// 明示的な named export に置き換えることでバンドラからも静的に見える形にする。
var sample_1 = require("./sample");
Object.defineProperty(exports, "Alexandria", { enumerable: true, get: function () { return sample_1.Alexandria; } });
Object.defineProperty(exports, "Cairo", { enumerable: true, get: function () { return sample_1.Cairo; } });
Object.defineProperty(exports, "Calendar", { enumerable: true, get: function () { return sample_1.Calendar; } });
Object.defineProperty(exports, "Jaypore", { enumerable: true, get: function () { return sample_1.Jaypore; } });
Object.defineProperty(exports, "London", { enumerable: true, get: function () { return sample_1.London; } });
Object.defineProperty(exports, "Madurai", { enumerable: true, get: function () { return sample_1.Madurai; } });
Object.defineProperty(exports, "NewYork", { enumerable: true, get: function () { return sample_1.NewYork; } });
Object.defineProperty(exports, "NewYork_Summer", { enumerable: true, get: function () { return sample_1.NewYork_Summer; } });
Object.defineProperty(exports, "Paris", { enumerable: true, get: function () { return sample_1.Paris; } });
Object.defineProperty(exports, "Romus", { enumerable: true, get: function () { return sample_1.Romus; } });
Object.defineProperty(exports, "mayaHaab", { enumerable: true, get: function () { return sample_1.mayaHaab; } });
Object.defineProperty(exports, "mayaLongCount", { enumerable: true, get: function () { return sample_1.mayaLongCount; } });
Object.defineProperty(exports, "mayaTzolkin", { enumerable: true, get: function () { return sample_1.mayaTzolkin; } });
Object.defineProperty(exports, "z\u00FCrich", { enumerable: true, get: function () { return sample_1.zürich; } });
Object.defineProperty(exports, "\u30A8\u30B8\u30D7\u30C8\u6708\u540D", { enumerable: true, get: function () { return sample_1.エジプト月名; } });
Object.defineProperty(exports, "\u30A8\u30EA\u30B9", { enumerable: true, get: function () { return sample_1.エリス; } });
Object.defineProperty(exports, "\u30AB\u30EA\u30B9\u30C8", { enumerable: true, get: function () { return sample_1.カリスト; } });
Object.defineProperty(exports, "\u30AB\u30ED\u30F3", { enumerable: true, get: function () { return sample_1.カロン; } });
Object.defineProperty(exports, "\u30AC\u30CB\u30E1\u30C7", { enumerable: true, get: function () { return sample_1.ガニメデ; } });
Object.defineProperty(exports, "\u30B3\u30D7\u30C8\u6708\u540D", { enumerable: true, get: function () { return sample_1.コプト月名; } });
Object.defineProperty(exports, "\u30BB\u30EC\u30B9", { enumerable: true, get: function () { return sample_1.セレス; } });
Object.defineProperty(exports, "\u30BF\u30A4\u30BF\u30F3", { enumerable: true, get: function () { return sample_1.タイタン; } });
Object.defineProperty(exports, "\u30C1\u30BF\u30CB\u30A2", { enumerable: true, get: function () { return sample_1.チタニア; } });
Object.defineProperty(exports, "\u30C7\u30A3\u30B9\u30CE\u30DF\u30A2", { enumerable: true, get: function () { return sample_1.ディスノミア; } });
Object.defineProperty(exports, "\u30C8\u30EA\u30C8\u30F3", { enumerable: true, get: function () { return sample_1.トリトン; } });
Object.defineProperty(exports, "\u30CA\u30DE\u30AB", { enumerable: true, get: function () { return sample_1.ナマカ; } });
Object.defineProperty(exports, "\u30CF\u30A6\u30E1\u30A2", { enumerable: true, get: function () { return sample_1.ハウメア; } });
Object.defineProperty(exports, "\u30D2\u30A4\u30A2\u30AB", { enumerable: true, get: function () { return sample_1.ヒイアカ; } });
Object.defineProperty(exports, "\u30DE\u30B1\u30DE\u30B1", { enumerable: true, get: function () { return sample_1.マケマケ; } });
Object.defineProperty(exports, "\u30DE\u30E4\u30C4\u30A9\u30EB\u30AD\u30F3", { enumerable: true, get: function () { return sample_1.マヤツォルキン; } });
Object.defineProperty(exports, "\u30DE\u30E4\u30CF\u30A2\u30D6", { enumerable: true, get: function () { return sample_1.マヤハアブ; } });
Object.defineProperty(exports, "\u30DE\u30E4\u30CF\u30A2\u30D6\u65E5", { enumerable: true, get: function () { return sample_1.マヤハアブ日; } });
Object.defineProperty(exports, "\u30ED\u30E0\u30EB\u30B9\u6708\u30E9\u30D9\u30EB\u30E9\u30C6\u30F3\u8A9E", { enumerable: true, get: function () { return sample_1.ロムルス月ラベルラテン語; } });
Object.defineProperty(exports, "\u30ED\u30E0\u30EB\u30B9\u6708\u30E9\u30D9\u30EB\u30E9\u30C6\u30F3\u8A9E\u304B\u306A", { enumerable: true, get: function () { return sample_1.ロムルス月ラベルラテン語かな; } });
Object.defineProperty(exports, "\u30ED\u30E0\u30EB\u30B9\u6708\u30E9\u30D9\u30EB\u6570\u5024", { enumerable: true, get: function () { return sample_1.ロムルス月ラベル数値; } });
Object.defineProperty(exports, "\u30ED\u30E0\u30EB\u30B9\u6708\u30E9\u30D9\u30EB\u6570\u5024\u304B\u306A", { enumerable: true, get: function () { return sample_1.ロムルス月ラベル数値かな; } });
Object.defineProperty(exports, "\u4E03\u5DFB\u518A\u5B50\u5143\u53F7", { enumerable: true, get: function () { return sample_1.七巻冊子元号; } });
Object.defineProperty(exports, "\u4E03\u66DC", { enumerable: true, get: function () { return sample_1.七曜; } });
Object.defineProperty(exports, "\u4E03\u66DC\u304B\u306A", { enumerable: true, get: function () { return sample_1.七曜かな; } });
Object.defineProperty(exports, "\u4E5D\u661F", { enumerable: true, get: function () { return sample_1.九星; } });
Object.defineProperty(exports, "\u4E5D\u661Frev", { enumerable: true, get: function () { return sample_1.九星rev; } });
Object.defineProperty(exports, "\u4E5D\u661F\u304B\u306A", { enumerable: true, get: function () { return sample_1.九星かな; } });
Object.defineProperty(exports, "\u4E5D\u661F\u304B\u306Arev", { enumerable: true, get: function () { return sample_1.九星かなrev; } });
Object.defineProperty(exports, "\u4E5D\u66DC", { enumerable: true, get: function () { return sample_1.九曜; } });
Object.defineProperty(exports, "\u4E5D\u66DC\u304B\u306A", { enumerable: true, get: function () { return sample_1.九曜かな; } });
Object.defineProperty(exports, "\u4E8C\u5341\u4E03\u5BBF", { enumerable: true, get: function () { return sample_1.二十七宿; } });
Object.defineProperty(exports, "\u4E8C\u5341\u4E03\u5BBF\u304B\u306A", { enumerable: true, get: function () { return sample_1.二十七宿かな; } });
Object.defineProperty(exports, "\u4E8C\u5341\u516B\u5BBF", { enumerable: true, get: function () { return sample_1.二十八宿; } });
Object.defineProperty(exports, "\u4E8C\u5341\u516B\u5BBF\u304B\u306A", { enumerable: true, get: function () { return sample_1.二十八宿かな; } });
Object.defineProperty(exports, "\u4E8C\u5341\u56DB\u7BC0\u5B63", { enumerable: true, get: function () { return sample_1.二十四節季; } });
Object.defineProperty(exports, "\u4E8C\u5341\u56DB\u7BC0\u5B63\u304B\u306A", { enumerable: true, get: function () { return sample_1.二十四節季かな; } });
Object.defineProperty(exports, "\u4F0A\u52E2\u4E4B\u5DFB\u5143\u53F7", { enumerable: true, get: function () { return sample_1.伊勢之巻元号; } });
Object.defineProperty(exports, "\u5143\u53F7", { enumerable: true, get: function () { return sample_1.元号; } });
Object.defineProperty(exports, "\u516D\u66DC", { enumerable: true, get: function () { return sample_1.六曜; } });
Object.defineProperty(exports, "\u516D\u66DC\u304B\u306A", { enumerable: true, get: function () { return sample_1.六曜かな; } });
Object.defineProperty(exports, "\u51A5\u738B\u661F", { enumerable: true, get: function () { return sample_1.冥王星; } });
Object.defineProperty(exports, "\u5317\u65B9\u7384\u6B66", { enumerable: true, get: function () { return sample_1.北方玄武; } });
Object.defineProperty(exports, "\u5317\u65B9\u7384\u6B66\u304B\u306A", { enumerable: true, get: function () { return sample_1.北方玄武かな; } });
Object.defineProperty(exports, "\u5317\u671D\u5143\u53F7", { enumerable: true, get: function () { return sample_1.北朝元号; } });
Object.defineProperty(exports, "\u5341\u4E8C\u652F", { enumerable: true, get: function () { return sample_1.十二支; } });
Object.defineProperty(exports, "\u5341\u4E8C\u652F\u304B\u306A", { enumerable: true, get: function () { return sample_1.十二支かな; } });
Object.defineProperty(exports, "\u5341\u5E72", { enumerable: true, get: function () { return sample_1.十干; } });
Object.defineProperty(exports, "\u5341\u5E72\u304B\u306A", { enumerable: true, get: function () { return sample_1.十干かな; } });
Object.defineProperty(exports, "\u5357\u65B9\u6731\u96C0", { enumerable: true, get: function () { return sample_1.南方朱雀; } });
Object.defineProperty(exports, "\u5357\u65B9\u6731\u96C0\u304B\u306A", { enumerable: true, get: function () { return sample_1.南方朱雀かな; } });
Object.defineProperty(exports, "\u5357\u65B9\u7D00\u4F1D\u5143\u53F7", { enumerable: true, get: function () { return sample_1.南方紀伝元号; } });
Object.defineProperty(exports, "\u5357\u671D\u5143\u53F7", { enumerable: true, get: function () { return sample_1.南朝元号; } });
Object.defineProperty(exports, "\u5357\u671D\u516C\u537F\u88DC\u4EFB\u5143\u53F7", { enumerable: true, get: function () { return sample_1.南朝公卿補任元号; } });
Object.defineProperty(exports, "\u5357\u671D\u7DE8\u5E74\u8A18\u7565\u5143\u53F7", { enumerable: true, get: function () { return sample_1.南朝編年記略元号; } });
Object.defineProperty(exports, "\u53F2\u6599\u521D\u51FA\u5143\u53F7", { enumerable: true, get: function () { return sample_1.史料初出元号; } });
Object.defineProperty(exports, "\u548C\u98A8\u6708\u540D", { enumerable: true, get: function () { return sample_1.和風月名; } });
Object.defineProperty(exports, "\u548C\u98A8\u6708\u540D\u304B\u306A", { enumerable: true, get: function () { return sample_1.和風月名かな; } });
Object.defineProperty(exports, "\u571F\u661F", { enumerable: true, get: function () { return sample_1.土星; } });
Object.defineProperty(exports, "\u5730\u7403", { enumerable: true, get: function () { return sample_1.地球; } });
Object.defineProperty(exports, "\u5929\u6587", { enumerable: true, get: function () { return sample_1.天文; } });
Object.defineProperty(exports, "\u5929\u6587\u5730\u7403", { enumerable: true, get: function () { return sample_1.天文地球; } });
Object.defineProperty(exports, "\u5929\u6587\u6708", { enumerable: true, get: function () { return sample_1.天文月; } });
Object.defineProperty(exports, "\u5929\u6587\u6771\u4EAC", { enumerable: true, get: function () { return sample_1.天文東京; } });
Object.defineProperty(exports, "\u5929\u6587\u706B\u661F", { enumerable: true, get: function () { return sample_1.天文火星; } });
Object.defineProperty(exports, "\u5929\u738B\u661F", { enumerable: true, get: function () { return sample_1.天王星; } });
Object.defineProperty(exports, "\u592A\u6B73", { enumerable: true, get: function () { return sample_1.太歳; } });
Object.defineProperty(exports, "\u592A\u967D", { enumerable: true, get: function () { return sample_1.太陽; } });
Object.defineProperty(exports, "\u6642\u9418", { enumerable: true, get: function () { return sample_1.時鐘; } });
Object.defineProperty(exports, "\u6642\u9418\u304B\u306A", { enumerable: true, get: function () { return sample_1.時鐘かな; } });
Object.defineProperty(exports, "\u6708", { enumerable: true, get: function () { return sample_1.月; } });
Object.defineProperty(exports, "\u6708\u76F8", { enumerable: true, get: function () { return sample_1.月相; } });
Object.defineProperty(exports, "\u6708\u76F8\u304B\u306A", { enumerable: true, get: function () { return sample_1.月相かな; } });
Object.defineProperty(exports, "\u6728\u661F", { enumerable: true, get: function () { return sample_1.木星; } });
Object.defineProperty(exports, "\u6771\u4EAC", { enumerable: true, get: function () { return sample_1.東京; } });
Object.defineProperty(exports, "\u6771\u65B9\u9752\u9F8D", { enumerable: true, get: function () { return sample_1.東方青龍; } });
Object.defineProperty(exports, "\u6771\u65B9\u9752\u9F8D\u304B\u306A", { enumerable: true, get: function () { return sample_1.東方青龍かな; } });
Object.defineProperty(exports, "\u6C34\u661F", { enumerable: true, get: function () { return sample_1.水星; } });
Object.defineProperty(exports, "\u6D77\u738B\u661F", { enumerable: true, get: function () { return sample_1.海王星; } });
Object.defineProperty(exports, "\u706B\u661F", { enumerable: true, get: function () { return sample_1.火星; } });
Object.defineProperty(exports, "\u767D\u5206\u6708", { enumerable: true, get: function () { return sample_1.白分月; } });
Object.defineProperty(exports, "\u7687\u4EE3\u8A18\u5143\u53F7", { enumerable: true, get: function () { return sample_1.皇代記元号; } });
Object.defineProperty(exports, "\u7D9A\u53F2\u611A\u6284\u5143\u53F7", { enumerable: true, get: function () { return sample_1.続史愚抄元号; } });
Object.defineProperty(exports, "\u897F\u65B9\u767E\u864E", { enumerable: true, get: function () { return sample_1.西方百虎; } });
Object.defineProperty(exports, "\u897F\u65B9\u767E\u864E\u304B\u306A", { enumerable: true, get: function () { return sample_1.西方百虎かな; } });
Object.defineProperty(exports, "\u91D1\u525B\u5BFA\u6587\u66F8\u5143\u53F7", { enumerable: true, get: function () { return sample_1.金剛寺文書元号; } });
Object.defineProperty(exports, "\u91D1\u661F", { enumerable: true, get: function () { return sample_1.金星; } });
Object.defineProperty(exports, "\u9ED2\u5206\u6708", { enumerable: true, get: function () { return sample_1.黒分月; } });
Object.defineProperty(exports, "\u9ED2\u5206\u6708\u8ECC\u9053", { enumerable: true, get: function () { return sample_1.黒分月軌道; } });
var fancy_date_1 = require("./fancy-date");
Object.defineProperty(exports, "FancyDate", { enumerable: true, get: function () { return fancy_date_1.FancyDate; } });
Object.defineProperty(exports, "EarthMoonOrbital", { enumerable: true, get: function () { return fancy_date_1.EarthMoonOrbital; } });
Object.defineProperty(exports, "EarthSolarOrbital", { enumerable: true, get: function () { return fancy_date_1.EarthSolarOrbital; } });
Object.defineProperty(exports, "MarsSolarOrbital", { enumerable: true, get: function () { return fancy_date_1.MarsSolarOrbital; } });
Object.defineProperty(exports, "MeanOrbital", { enumerable: true, get: function () { return fancy_date_1.MeanOrbital; } });
Object.defineProperty(exports, "MeanRotation", { enumerable: true, get: function () { return fancy_date_1.MeanRotation; } });
Object.defineProperty(exports, "TransformedOrbital", { enumerable: true, get: function () { return fancy_date_1.TransformedOrbital; } });
Object.defineProperty(exports, "bodyProfileOf", { enumerable: true, get: function () { return fancy_date_1.bodyProfileOf; } });
Object.defineProperty(exports, "centerOf", { enumerable: true, get: function () { return fancy_date_1.centerOf; } });
Object.defineProperty(exports, "hasLunarEvents", { enumerable: true, get: function () { return fancy_date_1.hasLunarEvents; } });
Object.defineProperty(exports, "hasLunarOrbitEvents", { enumerable: true, get: function () { return fancy_date_1.hasLunarOrbitEvents; } });
Object.defineProperty(exports, "hasSolarEvents", { enumerable: true, get: function () { return fancy_date_1.hasSolarEvents; } });
Object.defineProperty(exports, "isPlanetSkyBody", { enumerable: true, get: function () { return fancy_date_1.isPlanetSkyBody; } });
Object.defineProperty(exports, "orbitalOf", { enumerable: true, get: function () { return fancy_date_1.orbitalOf; } });
Object.defineProperty(exports, "placePlanet", { enumerable: true, get: function () { return fancy_date_1.placePlanet; } });
Object.defineProperty(exports, "placeSatellite", { enumerable: true, get: function () { return fancy_date_1.placeSatellite; } });
Object.defineProperty(exports, "placeStar", { enumerable: true, get: function () { return fancy_date_1.placeStar; } });
Object.defineProperty(exports, "prepareSpot", { enumerable: true, get: function () { return fancy_date_1.prepareSpot; } });
Object.defineProperty(exports, "prepareSpotModels", { enumerable: true, get: function () { return fancy_date_1.prepareSpotModels; } });
Object.defineProperty(exports, "resolveSkyBody", { enumerable: true, get: function () { return fancy_date_1.resolveSkyBody; } });
Object.defineProperty(exports, "rotationOf", { enumerable: true, get: function () { return fancy_date_1.rotationOf; } });
Object.defineProperty(exports, "transformOrbital", { enumerable: true, get: function () { return fancy_date_1.transformOrbital; } });
// orbital-model/mean/naoj/nasa/prepare の値・型はすべて './fancy-date' が
// 既に named export として再エクスポート済みなので、ここで重複して
// 再々エクスポートする必要はない。
var time_1 = require("./time");
Object.defineProperty(exports, "DAY", { enumerable: true, get: function () { return time_1.DAY; } });
Object.defineProperty(exports, "HOUR", { enumerable: true, get: function () { return time_1.HOUR; } });
Object.defineProperty(exports, "MINUTE", { enumerable: true, get: function () { return time_1.MINUTE; } });
Object.defineProperty(exports, "SECOND", { enumerable: true, get: function () { return time_1.SECOND; } });
Object.defineProperty(exports, "localTimezoneDeg", { enumerable: true, get: function () { return time_1.localTimezoneDeg; } });
Object.defineProperty(exports, "to_msec", { enumerable: true, get: function () { return time_1.to_msec; } });
Object.defineProperty(exports, "to_sec", { enumerable: true, get: function () { return time_1.to_sec; } });
Object.defineProperty(exports, "to_tempo_bare", { enumerable: true, get: function () { return time_1.to_tempo_bare; } });
Object.defineProperty(exports, "to_tempo_by", { enumerable: true, get: function () { return time_1.to_tempo_by; } });
Object.defineProperty(exports, "to_timezone_deg", { enumerable: true, get: function () { return time_1.to_timezone_deg; } });
var tempo_1 = require("./tempo");
Object.defineProperty(exports, "CachedTempoRule", { enumerable: true, get: function () { return tempo_1.CachedTempoRule; } });
Object.defineProperty(exports, "CyclicDayTempoRule", { enumerable: true, get: function () { return tempo_1.CyclicDayTempoRule; } });
Object.defineProperty(exports, "EraAdjustedTempoRule", { enumerable: true, get: function () { return tempo_1.EraAdjustedTempoRule; } });
Object.defineProperty(exports, "FixedTempoRule", { enumerable: true, get: function () { return tempo_1.FixedTempoRule; } });
Object.defineProperty(exports, "FloorTempoRule", { enumerable: true, get: function () { return tempo_1.FloorTempoRule; } });
Object.defineProperty(exports, "MeanLunarPhaseTempoRule", { enumerable: true, get: function () { return tempo_1.MeanLunarPhaseTempoRule; } });
Object.defineProperty(exports, "MeanLunisolarMonthRule", { enumerable: true, get: function () { return tempo_1.MeanLunisolarMonthRule; } });
Object.defineProperty(exports, "ObservedLunisolarMonthRule", { enumerable: true, get: function () { return tempo_1.ObservedLunisolarMonthRule; } });
Object.defineProperty(exports, "ObservedLunisolarYearRule", { enumerable: true, get: function () { return tempo_1.ObservedLunisolarYearRule; } });
Object.defineProperty(exports, "OrbitalPhaseTempoRule", { enumerable: true, get: function () { return tempo_1.OrbitalPhaseTempoRule; } });
Object.defineProperty(exports, "RealSunsetDayTempoRule", { enumerable: true, get: function () { return tempo_1.RealSunsetDayTempoRule; } });
Object.defineProperty(exports, "SolarEventDayTempoRule", { enumerable: true, get: function () { return tempo_1.SolarEventDayTempoRule; } });
Object.defineProperty(exports, "SolarDayHourTempoRule", { enumerable: true, get: function () { return tempo_1.SolarDayHourTempoRule; } });
Object.defineProperty(exports, "StartAlignedTempoRule", { enumerable: true, get: function () { return tempo_1.StartAlignedTempoRule; } });
Object.defineProperty(exports, "SubdivideTempoRule", { enumerable: true, get: function () { return tempo_1.SubdivideTempoRule; } });
Object.defineProperty(exports, "TableTempoRule", { enumerable: true, get: function () { return tempo_1.TableTempoRule; } });
Object.defineProperty(exports, "Tempo", { enumerable: true, get: function () { return tempo_1.Tempo; } });
Object.defineProperty(exports, "cyclic_label", { enumerable: true, get: function () { return tempo_1.cyclic_label; } });
Object.defineProperty(exports, "envelope_of", { enumerable: true, get: function () { return tempo_1.envelope_of; } });
Object.defineProperty(exports, "join", { enumerable: true, get: function () { return tempo_1.join; } });
var number_1 = require("./number");
Object.defineProperty(exports, "DIC", { enumerable: true, get: function () { return number_1.DIC; } });
Object.defineProperty(exports, "angle", { enumerable: true, get: function () { return number_1.angle; } });
Object.defineProperty(exports, "arabic", { enumerable: true, get: function () { return number_1.arabic; } });
Object.defineProperty(exports, "english", { enumerable: true, get: function () { return number_1.english; } });
Object.defineProperty(exports, "jpn", { enumerable: true, get: function () { return number_1.jpn; } });
Object.defineProperty(exports, "kor", { enumerable: true, get: function () { return number_1.kor; } });
Object.defineProperty(exports, "mod", { enumerable: true, get: function () { return number_1.mod; } });
Object.defineProperty(exports, "old_jpn", { enumerable: true, get: function () { return number_1.old_jpn; } });
Object.defineProperty(exports, "roman", { enumerable: true, get: function () { return number_1.roman; } });
var locale_registry_1 = require("./locale-registry");
Object.defineProperty(exports, "LOCALE_REGISTRY", { enumerable: true, get: function () { return locale_registry_1.LOCALE_REGISTRY; } });
Object.defineProperty(exports, "SCRIPT_REGISTRY", { enumerable: true, get: function () { return locale_registry_1.SCRIPT_REGISTRY; } });
Object.defineProperty(exports, "getLocale", { enumerable: true, get: function () { return locale_registry_1.getLocale; } });
Object.defineProperty(exports, "listLocales", { enumerable: true, get: function () { return locale_registry_1.listLocales; } });
//# sourceMappingURL=index.js.map