// この薄いラッパーは、`src/sample.ts` を `src/sample/` ディレクトリへ分割した際に
// 旧来のフラットな import 経路(`fancy-date/lib/sample`)を維持するために残している。
// export * from はコンパイル時に tslib.__exportStar() という実行時関数呼び出しになり、
// 静的な named export 解析に依存するバンドラで再エクスポート名が undefined になる
// 不具合があった(development-notes.md 参照)。明示的な named export に置き換える。
export {
  エジプト月名,
  コプト月名,
  タイ太陰月名,
  タイ太陰月名RTGS,
  マヤツォルキン,
  マヤハアブ,
  マヤハアブ日,
  ロムルス月ラベルラテン語,
  ロムルス月ラベルラテン語かな,
  ロムルス月ラベル数値,
  ロムルス月ラベル数値かな,
  七曜,
  七曜かな,
  九星,
  九星rev,
  九星かな,
  九星かなrev,
  九曜,
  九曜かな,
  二十七宿,
  二十七宿かな,
  二十八宿,
  二十八宿かな,
  二十四節季,
  二十四節季かな,
  六曜,
  六曜かな,
  北方玄武,
  北方玄武かな,
  十二支,
  十二支かな,
  十干,
  十干かな,
  南方朱雀,
  南方朱雀かな,
  和風月名,
  和風月名かな,
  時鐘,
  時鐘かな,
  月相,
  月相かな,
  東方青龍,
  東方青龍かな,
  西方百虎,
  西方百虎かな,
} from './sample/locale'

export {
  七巻冊子元号,
  伊勢之巻元号,
  元号,
  北朝元号,
  南方紀伝元号,
  南朝元号,
  南朝公卿補任元号,
  南朝編年記略元号,
  史料初出元号,
  皇代記元号,
  続史愚抄元号,
  金剛寺文書元号,
} from './sample/eras'

export {
  Alexandria,
  Bangkok,
  Cairo,
  Jaypore,
  London,
  Madurai,
  NewYork,
  NewYork_Summer,
  Paris,
  Romus,
  zürich,
  エリス,
  カリスト,
  カロン,
  ガニメデ,
  セレス,
  タイタン,
  チタニア,
  ディスノミア,
  トリトン,
  ナマカ,
  ハウメア,
  ヒイアカ,
  マケマケ,
  冥王星,
  土星,
  地球,
  天文地球,
  天文水星,
  天文金星,
  天文月,
  天文東京,
  天文火星,
  天文木星,
  天文土星,
  天文天王星,
  天文海王星,
  天文冥王星,
  天王星,
  太歳,
  太陽,
  月,
  木星,
  東京,
  水星,
  海王星,
  火星,
  白分月,
  金星,
  黒分月,
  黒分月軌道,
} from './sample/astro'

export { Calendar } from './sample/calendars'
export { CHURCH_FEAST_LABELS, churchFeastDates, churchFeastNotes } from './sample/derived/church'
export {
  THAI_BUDDHIST_FEAST_LABELS,
  thaiBuddhistFeastDates,
  thaiBuddhistFeastNotes,
} from './sample/derived/thai'
export { mayaHaab, mayaLongCount, mayaTzolkin } from './sample/derived/maya'
export {
  matchesPanchanga,
  panchanga,
  panchangaCandidates,
  panchangaNotes,
} from './sample/derived/panchanga'
export type { Panchanga, PanchangaCondition, PanchangaNoteRule } from './sample/derived/panchanga'
export type { ChurchFeastDate, ChurchFeastOptions } from './sample/derived/church'
export type { ThaiBuddhistFeastDate, ThaiBuddhistFeastOptions } from './sample/derived/thai'
